// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: llm_request.proto

#include "llm_request.pb.h"
#include "llm_request.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace llm_request {

static const char* AskLLMQuestion_method_names[] = {
  "/llm_request.AskLLMQuestion/PromptLLM",
};

std::unique_ptr< AskLLMQuestion::Stub> AskLLMQuestion::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AskLLMQuestion::Stub> stub(new AskLLMQuestion::Stub(channel));
  return stub;
}

AskLLMQuestion::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_PromptLLM_(AskLLMQuestion_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AskLLMQuestion::Stub::PromptLLM(::grpc::ClientContext* context, const ::llm_request::LLMInit& request, ::llm_request::LLMInference* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_PromptLLM_, context, request, response);
}

void AskLLMQuestion::Stub::experimental_async::PromptLLM(::grpc::ClientContext* context, const ::llm_request::LLMInit* request, ::llm_request::LLMInference* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_PromptLLM_, context, request, response, std::move(f));
}

void AskLLMQuestion::Stub::experimental_async::PromptLLM(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::llm_request::LLMInference* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_PromptLLM_, context, request, response, std::move(f));
}

void AskLLMQuestion::Stub::experimental_async::PromptLLM(::grpc::ClientContext* context, const ::llm_request::LLMInit* request, ::llm_request::LLMInference* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_PromptLLM_, context, request, response, reactor);
}

void AskLLMQuestion::Stub::experimental_async::PromptLLM(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::llm_request::LLMInference* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_PromptLLM_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::llm_request::LLMInference>* AskLLMQuestion::Stub::AsyncPromptLLMRaw(::grpc::ClientContext* context, const ::llm_request::LLMInit& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::llm_request::LLMInference>::Create(channel_.get(), cq, rpcmethod_PromptLLM_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::llm_request::LLMInference>* AskLLMQuestion::Stub::PrepareAsyncPromptLLMRaw(::grpc::ClientContext* context, const ::llm_request::LLMInit& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::llm_request::LLMInference>::Create(channel_.get(), cq, rpcmethod_PromptLLM_, context, request, false);
}

AskLLMQuestion::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AskLLMQuestion_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AskLLMQuestion::Service, ::llm_request::LLMInit, ::llm_request::LLMInference>(
          [](AskLLMQuestion::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::llm_request::LLMInit* req,
             ::llm_request::LLMInference* resp) {
               return service->PromptLLM(ctx, req, resp);
             }, this)));
}

AskLLMQuestion::Service::~Service() {
}

::grpc::Status AskLLMQuestion::Service::PromptLLM(::grpc::ServerContext* context, const ::llm_request::LLMInit* request, ::llm_request::LLMInference* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace llm_request

