// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: llm_request.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_llm_5frequest_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_llm_5frequest_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_llm_5frequest_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_llm_5frequest_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_llm_5frequest_2eproto;
namespace llm_request {
class LLMInference;
struct LLMInferenceDefaultTypeInternal;
extern LLMInferenceDefaultTypeInternal _LLMInference_default_instance_;
class LLMInit;
struct LLMInitDefaultTypeInternal;
extern LLMInitDefaultTypeInternal _LLMInit_default_instance_;
}  // namespace llm_request
PROTOBUF_NAMESPACE_OPEN
template<> ::llm_request::LLMInference* Arena::CreateMaybeMessage<::llm_request::LLMInference>(Arena*);
template<> ::llm_request::LLMInit* Arena::CreateMaybeMessage<::llm_request::LLMInit>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace llm_request {

// ===================================================================

class LLMInit final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:llm_request.LLMInit) */ {
 public:
  inline LLMInit() : LLMInit(nullptr) {}
  ~LLMInit() override;
  explicit PROTOBUF_CONSTEXPR LLMInit(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LLMInit(const LLMInit& from);
  LLMInit(LLMInit&& from) noexcept
    : LLMInit() {
    *this = ::std::move(from);
  }

  inline LLMInit& operator=(const LLMInit& from) {
    CopyFrom(from);
    return *this;
  }
  inline LLMInit& operator=(LLMInit&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LLMInit& default_instance() {
    return *internal_default_instance();
  }
  static inline const LLMInit* internal_default_instance() {
    return reinterpret_cast<const LLMInit*>(
               &_LLMInit_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LLMInit& a, LLMInit& b) {
    a.Swap(&b);
  }
  inline void Swap(LLMInit* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LLMInit* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LLMInit* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LLMInit>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LLMInit& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LLMInit& from) {
    LLMInit::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LLMInit* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "llm_request.LLMInit";
  }
  protected:
  explicit LLMInit(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kApiKeyFieldNumber = 1,
    kPromptFieldNumber = 2,
  };
  // string apiKey = 1;
  void clear_apikey();
  const std::string& apikey() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_apikey(ArgT0&& arg0, ArgT... args);
  std::string* mutable_apikey();
  PROTOBUF_NODISCARD std::string* release_apikey();
  void set_allocated_apikey(std::string* apikey);
  private:
  const std::string& _internal_apikey() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_apikey(const std::string& value);
  std::string* _internal_mutable_apikey();
  public:

  // string prompt = 2;
  void clear_prompt();
  const std::string& prompt() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_prompt(ArgT0&& arg0, ArgT... args);
  std::string* mutable_prompt();
  PROTOBUF_NODISCARD std::string* release_prompt();
  void set_allocated_prompt(std::string* prompt);
  private:
  const std::string& _internal_prompt() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_prompt(const std::string& value);
  std::string* _internal_mutable_prompt();
  public:

  // @@protoc_insertion_point(class_scope:llm_request.LLMInit)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr apikey_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr prompt_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_llm_5frequest_2eproto;
};
// -------------------------------------------------------------------

class LLMInference final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:llm_request.LLMInference) */ {
 public:
  inline LLMInference() : LLMInference(nullptr) {}
  ~LLMInference() override;
  explicit PROTOBUF_CONSTEXPR LLMInference(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LLMInference(const LLMInference& from);
  LLMInference(LLMInference&& from) noexcept
    : LLMInference() {
    *this = ::std::move(from);
  }

  inline LLMInference& operator=(const LLMInference& from) {
    CopyFrom(from);
    return *this;
  }
  inline LLMInference& operator=(LLMInference&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LLMInference& default_instance() {
    return *internal_default_instance();
  }
  static inline const LLMInference* internal_default_instance() {
    return reinterpret_cast<const LLMInference*>(
               &_LLMInference_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(LLMInference& a, LLMInference& b) {
    a.Swap(&b);
  }
  inline void Swap(LLMInference* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LLMInference* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LLMInference* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LLMInference>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LLMInference& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LLMInference& from) {
    LLMInference::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LLMInference* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "llm_request.LLMInference";
  }
  protected:
  explicit LLMInference(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAnswerFieldNumber = 1,
  };
  // string answer = 1;
  void clear_answer();
  const std::string& answer() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_answer(ArgT0&& arg0, ArgT... args);
  std::string* mutable_answer();
  PROTOBUF_NODISCARD std::string* release_answer();
  void set_allocated_answer(std::string* answer);
  private:
  const std::string& _internal_answer() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_answer(const std::string& value);
  std::string* _internal_mutable_answer();
  public:

  // @@protoc_insertion_point(class_scope:llm_request.LLMInference)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr answer_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_llm_5frequest_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LLMInit

// string apiKey = 1;
inline void LLMInit::clear_apikey() {
  _impl_.apikey_.ClearToEmpty();
}
inline const std::string& LLMInit::apikey() const {
  // @@protoc_insertion_point(field_get:llm_request.LLMInit.apiKey)
  return _internal_apikey();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LLMInit::set_apikey(ArgT0&& arg0, ArgT... args) {
 
 _impl_.apikey_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:llm_request.LLMInit.apiKey)
}
inline std::string* LLMInit::mutable_apikey() {
  std::string* _s = _internal_mutable_apikey();
  // @@protoc_insertion_point(field_mutable:llm_request.LLMInit.apiKey)
  return _s;
}
inline const std::string& LLMInit::_internal_apikey() const {
  return _impl_.apikey_.Get();
}
inline void LLMInit::_internal_set_apikey(const std::string& value) {
  
  _impl_.apikey_.Set(value, GetArenaForAllocation());
}
inline std::string* LLMInit::_internal_mutable_apikey() {
  
  return _impl_.apikey_.Mutable(GetArenaForAllocation());
}
inline std::string* LLMInit::release_apikey() {
  // @@protoc_insertion_point(field_release:llm_request.LLMInit.apiKey)
  return _impl_.apikey_.Release();
}
inline void LLMInit::set_allocated_apikey(std::string* apikey) {
  if (apikey != nullptr) {
    
  } else {
    
  }
  _impl_.apikey_.SetAllocated(apikey, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.apikey_.IsDefault()) {
    _impl_.apikey_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:llm_request.LLMInit.apiKey)
}

// string prompt = 2;
inline void LLMInit::clear_prompt() {
  _impl_.prompt_.ClearToEmpty();
}
inline const std::string& LLMInit::prompt() const {
  // @@protoc_insertion_point(field_get:llm_request.LLMInit.prompt)
  return _internal_prompt();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LLMInit::set_prompt(ArgT0&& arg0, ArgT... args) {
 
 _impl_.prompt_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:llm_request.LLMInit.prompt)
}
inline std::string* LLMInit::mutable_prompt() {
  std::string* _s = _internal_mutable_prompt();
  // @@protoc_insertion_point(field_mutable:llm_request.LLMInit.prompt)
  return _s;
}
inline const std::string& LLMInit::_internal_prompt() const {
  return _impl_.prompt_.Get();
}
inline void LLMInit::_internal_set_prompt(const std::string& value) {
  
  _impl_.prompt_.Set(value, GetArenaForAllocation());
}
inline std::string* LLMInit::_internal_mutable_prompt() {
  
  return _impl_.prompt_.Mutable(GetArenaForAllocation());
}
inline std::string* LLMInit::release_prompt() {
  // @@protoc_insertion_point(field_release:llm_request.LLMInit.prompt)
  return _impl_.prompt_.Release();
}
inline void LLMInit::set_allocated_prompt(std::string* prompt) {
  if (prompt != nullptr) {
    
  } else {
    
  }
  _impl_.prompt_.SetAllocated(prompt, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.prompt_.IsDefault()) {
    _impl_.prompt_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:llm_request.LLMInit.prompt)
}

// -------------------------------------------------------------------

// LLMInference

// string answer = 1;
inline void LLMInference::clear_answer() {
  _impl_.answer_.ClearToEmpty();
}
inline const std::string& LLMInference::answer() const {
  // @@protoc_insertion_point(field_get:llm_request.LLMInference.answer)
  return _internal_answer();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LLMInference::set_answer(ArgT0&& arg0, ArgT... args) {
 
 _impl_.answer_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:llm_request.LLMInference.answer)
}
inline std::string* LLMInference::mutable_answer() {
  std::string* _s = _internal_mutable_answer();
  // @@protoc_insertion_point(field_mutable:llm_request.LLMInference.answer)
  return _s;
}
inline const std::string& LLMInference::_internal_answer() const {
  return _impl_.answer_.Get();
}
inline void LLMInference::_internal_set_answer(const std::string& value) {
  
  _impl_.answer_.Set(value, GetArenaForAllocation());
}
inline std::string* LLMInference::_internal_mutable_answer() {
  
  return _impl_.answer_.Mutable(GetArenaForAllocation());
}
inline std::string* LLMInference::release_answer() {
  // @@protoc_insertion_point(field_release:llm_request.LLMInference.answer)
  return _impl_.answer_.Release();
}
inline void LLMInference::set_allocated_answer(std::string* answer) {
  if (answer != nullptr) {
    
  } else {
    
  }
  _impl_.answer_.SetAllocated(answer, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.answer_.IsDefault()) {
    _impl_.answer_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:llm_request.LLMInference.answer)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace llm_request

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_llm_5frequest_2eproto
